# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (17)
# #########################################################################

class CandidateFact(BaseModel):
    idx: typing.Optional[int] = Field(default=None, description='Index of this fact in the candidates list')
    subject: typing.Optional[str] = None
    predicate: typing.Optional[str] = None
    object: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

class CodingMemoryExtraction(BaseModel):
    decisions: typing.List["ExtractedDecision"]
    gotchas: typing.List["ExtractedGotcha"]
    dead_ends: typing.List["ExtractedDeadEnd"]
    preferences: typing.List["ExtractedCodingPreference"]

class CodingSessionContext(BaseModel):
    branch: typing.Optional[str] = Field(default=None, description='The git branch the session is working on')
    task: typing.Optional[str] = Field(default=None, description='Ticket ID (e.g. MUD-395) or the stated goal of the session; null if unknown')
    files: typing.List[str] = Field(description='File paths this session has touched so far')

class ContradictionResult(BaseModel):
    contradicted_indices: typing.List[int] = Field(description='Indices of candidate facts that are contradicted by the new fact. Empty if no contradictions.')
    contradiction_type: typing.Optional[str] = Field(default=None, description='Type: \'direct_supersession\' (same subject, updated value), \'negation\' (opposite claim), \'refinement\' (more specific version), or \'none\'')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of why these facts are contradicted')

class CuratedMemories(BaseModel):
    verdicts: typing.List["CuratorVerdict"] = Field(description='exactly one entry per candidate, including rejects')

class CuratorVerdict(BaseModel):
    id: typing.Optional[int] = Field(default=None, description='the candidate\'s id, exactly as given')
    action: typing.Optional[types.CurateAction] = None
    known_as: typing.Optional[int] = Field(default=None, description='for ALREADY_KNOWN and SUPERSEDES: the number of the existing lesson it matches or replaces; null otherwise')

class ExtractedCodingPreference(BaseModel):
    category: typing.Optional[str] = Field(default=None, description='Preference category: e.g. testing, style, tooling, workflow')
    preference: typing.Optional[str] = Field(default=None, description='The stated preference about how to work')
    confidence: typing.Optional[float] = Field(default=None, description='Extraction confidence from 0.0 to 1.0')

class ExtractedDeadEnd(BaseModel):
    symptom: typing.Optional[str] = Field(default=None, description='The observable failure: the error text or behaviour that showed the attempt did not work. Quote the transcript where possible. Null only if nothing observable was shown.')
    attempt: typing.Optional[str] = Field(default=None, description='What was tried')
    why_failed: typing.Optional[str] = Field(default=None, description='Why it failed, as stated in the transcript')
    anchor_files: typing.List[str] = Field(description='Subset of context.files this dead end is about; empty if none apply')
    concerns_task: typing.Optional[bool] = Field(default=None, description='True if the dead end is about context.task')
    confidence: typing.Optional[float] = Field(default=None, description='Extraction confidence from 0.0 to 1.0')

class ExtractedDecision(BaseModel):
    text: typing.Optional[str] = Field(default=None, description='The decision as one sentence: chose X over Y')
    reason: typing.Optional[str] = Field(default=None, description='Why, as stated in the transcript')
    anchor_files: typing.List[str] = Field(description='Subset of context.files this decision is about; empty if none apply')
    concerns_task: typing.Optional[bool] = Field(default=None, description='True if the decision is about context.task')
    confidence: typing.Optional[float] = Field(default=None, description='Extraction confidence from 0.0 to 1.0')

class ExtractedGotcha(BaseModel):
    symptom: typing.Optional[str] = Field(default=None, description='What a future agent would observe before knowing this: the error text, the failing command, or the condition that triggers it. Quote the transcript where possible. Null only if nothing observable was shown.')
    text: typing.Optional[str] = Field(default=None, description='The constraint, one sentence, imperative where possible')
    anchor_files: typing.List[str] = Field(description='Subset of context.files this gotcha is about; empty if none apply')
    concerns_task: typing.Optional[bool] = Field(default=None, description='True if the gotcha is about context.task')
    confidence: typing.Optional[float] = Field(default=None, description='Extraction confidence from 0.0 to 1.0')

class ExtractedReasoningStep(BaseModel):
    thought: typing.Optional[str] = Field(default=None, description='The reasoning or hypothesis behind the action — WHY it was done')
    action: typing.Optional[str] = Field(default=None, description='What action was taken or decision made')
    observation: typing.Optional[str] = Field(default=None, description='What was learned or observed from the action')
    alternatives_considered: typing.Optional[str] = Field(default=None, description='Other approaches that were weighed and rejected')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in the extraction, 0.0 to 1.0')

class ReasoningChainInput(BaseModel):
    task: typing.Optional[str] = Field(default=None, description='The task that was solved')
    steps: typing.List["ReasoningStepInput"] = Field(description='The reasoning steps taken')
    outcome: typing.Optional[str] = Field(default=None, description='The final outcome')

class ReasoningExtractionOutput(BaseModel):
    task: typing.Optional[str] = Field(default=None, description='The overall task or question being addressed')
    steps: typing.List["ExtractedReasoningStep"] = Field(description='The reasoning steps in chronological order')
    final_conclusion: typing.Optional[str] = Field(default=None, description='The final conclusion or answer reached')
    success: typing.Optional[bool] = Field(default=None, description='Whether the task was successfully completed')

class ReasoningStepInput(BaseModel):
    thought: typing.Optional[str] = Field(default=None, description='Why this action was chosen')
    action: typing.Optional[str] = Field(default=None, description='What was done')
    observation: typing.Optional[str] = Field(default=None, description='What was learned')

class RecallScreen(BaseModel):
    verdicts: typing.List["RecallVerdict"] = Field(description='exactly one entry per candidate, including rejects')

class RecallVerdict(BaseModel):
    id: typing.Optional[int] = Field(default=None, description='the candidate\'s id, exactly as given')
    keep: typing.Optional[bool] = Field(default=None, description='true only if this candidate genuinely bears on the query')

class TemporalExtraction(BaseModel):
    valid_at: typing.Optional[str] = Field(default=None, description='Extracted datetime when fact became true, in ISO 8601. E.g., \'2026-03-01T00:00:00Z\'. null if not determinable.')
    temporal_qualifier: typing.Optional[str] = Field(default=None, description='Temporal qualifier: \'since\', \'until\', \'as_of\', \'formerly\', \'currently\', or null')
    is_current_state: typing.Optional[bool] = Field(default=None, description='True if this describes the current state of affairs, false if explicitly past tense')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
