# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def CurateCodingMemory(self, candidates: str,existing: str,transcript: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CuratedMemories:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.CurateCodingMemory(candidates=candidates,existing=existing,transcript=transcript,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="CurateCodingMemory", args={
                "candidates": candidates,"existing": existing,"transcript": transcript,
            })
            return typing.cast(types.CuratedMemories, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def DetectContradictions(self, new_fact_subject: str,new_fact_predicate: str,new_fact_object: str,candidates: typing.List["types.CandidateFact"],
        baml_options: BamlCallOptions = {},
    ) -> types.ContradictionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DetectContradictions(new_fact_subject=new_fact_subject,new_fact_predicate=new_fact_predicate,new_fact_object=new_fact_object,candidates=candidates,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DetectContradictions", args={
                "new_fact_subject": new_fact_subject,"new_fact_predicate": new_fact_predicate,"new_fact_object": new_fact_object,"candidates": candidates,
            })
            return typing.cast(types.ContradictionResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractCodingMemory(self, transcript: str,context: types.CodingSessionContext,
        baml_options: BamlCallOptions = {},
    ) -> types.CodingMemoryExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractCodingMemory(transcript=transcript,context=context,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractCodingMemory", args={
                "transcript": transcript,"context": context,
            })
            return typing.cast(types.CodingMemoryExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractReasoning(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ReasoningExtractionOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractReasoning(text=text,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractReasoning", args={
                "text": text,
            })
            return typing.cast(types.ReasoningExtractionOutput, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTemporalContext(self, text: str,reference_time: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TemporalExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractTemporalContext(text=text,reference_time=reference_time,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTemporalContext", args={
                "text": text,"reference_time": reference_time,
            })
            return typing.cast(types.TemporalExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ScreenRecalledMemories(self, query: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RecallScreen:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ScreenRecalledMemories(query=query,candidates=candidates,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ScreenRecalledMemories", args={
                "query": query,"candidates": candidates,
            })
            return typing.cast(types.RecallScreen, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeExplanation(self, chain: types.ReasoningChainInput,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SynthesizeExplanation(chain=chain,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeExplanation", args={
                "chain": chain,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CurateCodingMemory(self, candidates: str,existing: str,transcript: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CuratedMemories, types.CuratedMemories]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="CurateCodingMemory", args={
            "candidates": candidates,"existing": existing,"transcript": transcript,
        })
        return baml_py.BamlSyncStream[stream_types.CuratedMemories, types.CuratedMemories](
          __result__,
          lambda x: typing.cast(stream_types.CuratedMemories, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CuratedMemories, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DetectContradictions(self, new_fact_subject: str,new_fact_predicate: str,new_fact_object: str,candidates: typing.List["types.CandidateFact"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ContradictionResult, types.ContradictionResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DetectContradictions", args={
            "new_fact_subject": new_fact_subject,"new_fact_predicate": new_fact_predicate,"new_fact_object": new_fact_object,"candidates": candidates,
        })
        return baml_py.BamlSyncStream[stream_types.ContradictionResult, types.ContradictionResult](
          __result__,
          lambda x: typing.cast(stream_types.ContradictionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ContradictionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractCodingMemory(self, transcript: str,context: types.CodingSessionContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CodingMemoryExtraction, types.CodingMemoryExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractCodingMemory", args={
            "transcript": transcript,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.CodingMemoryExtraction, types.CodingMemoryExtraction](
          __result__,
          lambda x: typing.cast(stream_types.CodingMemoryExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CodingMemoryExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractReasoning(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ReasoningExtractionOutput, types.ReasoningExtractionOutput]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractReasoning", args={
            "text": text,
        })
        return baml_py.BamlSyncStream[stream_types.ReasoningExtractionOutput, types.ReasoningExtractionOutput](
          __result__,
          lambda x: typing.cast(stream_types.ReasoningExtractionOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ReasoningExtractionOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractTemporalContext(self, text: str,reference_time: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TemporalExtraction, types.TemporalExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTemporalContext", args={
            "text": text,"reference_time": reference_time,
        })
        return baml_py.BamlSyncStream[stream_types.TemporalExtraction, types.TemporalExtraction](
          __result__,
          lambda x: typing.cast(stream_types.TemporalExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TemporalExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ScreenRecalledMemories(self, query: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RecallScreen, types.RecallScreen]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ScreenRecalledMemories", args={
            "query": query,"candidates": candidates,
        })
        return baml_py.BamlSyncStream[stream_types.RecallScreen, types.RecallScreen](
          __result__,
          lambda x: typing.cast(stream_types.RecallScreen, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RecallScreen, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeExplanation(self, chain: types.ReasoningChainInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeExplanation", args={
            "chain": chain,
        })
        return baml_py.BamlSyncStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CurateCodingMemory(self, candidates: str,existing: str,transcript: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CurateCodingMemory", args={
            "candidates": candidates,"existing": existing,"transcript": transcript,
        }, mode="request")
        return __result__
    def DetectContradictions(self, new_fact_subject: str,new_fact_predicate: str,new_fact_object: str,candidates: typing.List["types.CandidateFact"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetectContradictions", args={
            "new_fact_subject": new_fact_subject,"new_fact_predicate": new_fact_predicate,"new_fact_object": new_fact_object,"candidates": candidates,
        }, mode="request")
        return __result__
    def ExtractCodingMemory(self, transcript: str,context: types.CodingSessionContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractCodingMemory", args={
            "transcript": transcript,"context": context,
        }, mode="request")
        return __result__
    def ExtractReasoning(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractReasoning", args={
            "text": text,
        }, mode="request")
        return __result__
    def ExtractTemporalContext(self, text: str,reference_time: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTemporalContext", args={
            "text": text,"reference_time": reference_time,
        }, mode="request")
        return __result__
    def ScreenRecalledMemories(self, query: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScreenRecalledMemories", args={
            "query": query,"candidates": candidates,
        }, mode="request")
        return __result__
    def SynthesizeExplanation(self, chain: types.ReasoningChainInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeExplanation", args={
            "chain": chain,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CurateCodingMemory(self, candidates: str,existing: str,transcript: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CurateCodingMemory", args={
            "candidates": candidates,"existing": existing,"transcript": transcript,
        }, mode="stream")
        return __result__
    def DetectContradictions(self, new_fact_subject: str,new_fact_predicate: str,new_fact_object: str,candidates: typing.List["types.CandidateFact"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetectContradictions", args={
            "new_fact_subject": new_fact_subject,"new_fact_predicate": new_fact_predicate,"new_fact_object": new_fact_object,"candidates": candidates,
        }, mode="stream")
        return __result__
    def ExtractCodingMemory(self, transcript: str,context: types.CodingSessionContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractCodingMemory", args={
            "transcript": transcript,"context": context,
        }, mode="stream")
        return __result__
    def ExtractReasoning(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractReasoning", args={
            "text": text,
        }, mode="stream")
        return __result__
    def ExtractTemporalContext(self, text: str,reference_time: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTemporalContext", args={
            "text": text,"reference_time": reference_time,
        }, mode="stream")
        return __result__
    def ScreenRecalledMemories(self, query: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ScreenRecalledMemories", args={
            "query": query,"candidates": candidates,
        }, mode="stream")
        return __result__
    def SynthesizeExplanation(self, chain: types.ReasoningChainInput,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeExplanation", args={
            "chain": chain,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))