# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class CurateAction(str, Enum):
    WRITE = "WRITE"
    ALREADY_KNOWN = "ALREADY_KNOWN"
    SUPERSEDES = "SUPERSEDES"
    NOT_DURABLE = "NOT_DURABLE"
    UNSUPPORTED = "UNSUPPORTED"

class ServedOutcome(str, Enum):
    HELPFUL = "HELPFUL"
    HARMFUL = "HARMFUL"
    UNUSED = "UNUSED"

# #########################################################################
# Generated classes (19)
# #########################################################################

class CandidateFact(BaseModel):
    idx: int = Field(description='Index of this fact in the candidates list')
    subject: str
    predicate: str
    object: str
    confidence: float

class CodingMemoryExtraction(BaseModel):
    decisions: typing.List["ExtractedDecision"]
    gotchas: typing.List["ExtractedGotcha"]
    dead_ends: typing.List["ExtractedDeadEnd"]
    preferences: typing.List["ExtractedCodingPreference"]

class CodingSessionContext(BaseModel):
    branch: str = Field(description='The git branch the session is working on')
    task: typing.Optional[str] = Field(default=None, description='Ticket ID (e.g. MUD-395) or the stated goal of the session; null if unknown')
    files: typing.List[str] = Field(description='File paths this session has touched so far')

class ContradictionResult(BaseModel):
    contradicted_indices: typing.List[int] = Field(description='Indices of candidate facts that are contradicted by the new fact. Empty if no contradictions.')
    contradiction_type: str = Field(description='Type: \'direct_supersession\' (same subject, updated value), \'negation\' (opposite claim), \'refinement\' (more specific version), or \'none\'')
    reasoning: str = Field(description='Brief explanation of why these facts are contradicted')

class CuratedMemories(BaseModel):
    verdicts: typing.List["CuratorVerdict"] = Field(description='exactly one entry per candidate, including rejects')

class CuratorVerdict(BaseModel):
    id: int = Field(description='the candidate\'s id, exactly as given')
    action: CurateAction
    known_as: typing.Optional[int] = Field(default=None, description='for ALREADY_KNOWN and SUPERSEDES: the number of the existing lesson it matches or replaces; null otherwise')

class ExtractedCodingPreference(BaseModel):
    category: str = Field(description='Preference category: e.g. testing, style, tooling, workflow')
    preference: str = Field(description='The stated preference about how to work')
    confidence: float = Field(description='Extraction confidence from 0.0 to 1.0')

class ExtractedDeadEnd(BaseModel):
    symptom: typing.Optional[str] = Field(default=None, description='The observable failure: the error text or behaviour that showed the attempt did not work. Quote the transcript where possible. Null only if nothing observable was shown.')
    attempt: str = Field(description='What was tried')
    why_failed: str = Field(description='Why it failed, as stated in the transcript')
    anchor_files: typing.List[str] = Field(description='Subset of context.files this dead end is about; empty if none apply')
    concerns_task: bool = Field(description='True if the dead end is about context.task')
    confidence: float = Field(description='Extraction confidence from 0.0 to 1.0')

class ExtractedDecision(BaseModel):
    text: str = Field(description='The decision as one sentence: chose X over Y')
    reason: str = Field(description='Why, as stated in the transcript')
    anchor_files: typing.List[str] = Field(description='Subset of context.files this decision is about; empty if none apply')
    concerns_task: bool = Field(description='True if the decision is about context.task')
    confidence: float = Field(description='Extraction confidence from 0.0 to 1.0')

class ExtractedGotcha(BaseModel):
    symptom: typing.Optional[str] = Field(default=None, description='What a future agent would observe before knowing this: the error text, the failing command, or the condition that triggers it. Quote the transcript where possible. Null only if nothing observable was shown.')
    text: str = Field(description='The constraint, one sentence, imperative where possible')
    anchor_files: typing.List[str] = Field(description='Subset of context.files this gotcha is about; empty if none apply')
    concerns_task: bool = Field(description='True if the gotcha is about context.task')
    confidence: float = Field(description='Extraction confidence from 0.0 to 1.0')

class ExtractedReasoningStep(BaseModel):
    thought: str = Field(description='The reasoning or hypothesis behind the action — WHY it was done')
    action: str = Field(description='What action was taken or decision made')
    observation: str = Field(description='What was learned or observed from the action')
    alternatives_considered: typing.Optional[str] = Field(default=None, description='Other approaches that were weighed and rejected')
    confidence: float = Field(description='Confidence in the extraction, 0.0 to 1.0')

class ReasoningChainInput(BaseModel):
    task: str = Field(description='The task that was solved')
    steps: typing.List["ReasoningStepInput"] = Field(description='The reasoning steps taken')
    outcome: str = Field(description='The final outcome')

class ReasoningExtractionOutput(BaseModel):
    task: str = Field(description='The overall task or question being addressed')
    steps: typing.List["ExtractedReasoningStep"] = Field(description='The reasoning steps in chronological order')
    final_conclusion: str = Field(description='The final conclusion or answer reached')
    success: bool = Field(description='Whether the task was successfully completed')

class ReasoningStepInput(BaseModel):
    thought: str = Field(description='Why this action was chosen')
    action: str = Field(description='What was done')
    observation: str = Field(description='What was learned')

class RecallScreen(BaseModel):
    verdicts: typing.List["RecallVerdict"] = Field(description='exactly one entry per candidate, including rejects')

class RecallVerdict(BaseModel):
    id: int = Field(description='the candidate\'s id, exactly as given')
    keep: bool = Field(description='true only if this candidate genuinely bears on the query')

class ServedRatings(BaseModel):
    verdicts: typing.List["ServedVerdict"] = Field(description='exactly one entry per lesson, including the unused ones')

class ServedVerdict(BaseModel):
    id: int = Field(description='the lesson\'s id, exactly as given')
    outcome: ServedOutcome

class TemporalExtraction(BaseModel):
    valid_at: typing.Optional[str] = Field(default=None, description='Extracted datetime when fact became true, in ISO 8601. E.g., \'2026-03-01T00:00:00Z\'. null if not determinable.')
    temporal_qualifier: typing.Optional[str] = Field(default=None, description='Temporal qualifier: \'since\', \'until\', \'as_of\', \'formerly\', \'currently\', or null')
    is_current_state: bool = Field(description='True if this describes the current state of affairs, false if explicitly past tense')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
