# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CandidateFact": types.CandidateFact,
    "stream_types.CandidateFact": stream_types.CandidateFact,

    "types.CodingMemoryExtraction": types.CodingMemoryExtraction,
    "stream_types.CodingMemoryExtraction": stream_types.CodingMemoryExtraction,

    "types.CodingSessionContext": types.CodingSessionContext,
    "stream_types.CodingSessionContext": stream_types.CodingSessionContext,

    "types.ContradictionResult": types.ContradictionResult,
    "stream_types.ContradictionResult": stream_types.ContradictionResult,

    "types.ExtractedCodingPreference": types.ExtractedCodingPreference,
    "stream_types.ExtractedCodingPreference": stream_types.ExtractedCodingPreference,

    "types.ExtractedDeadEnd": types.ExtractedDeadEnd,
    "stream_types.ExtractedDeadEnd": stream_types.ExtractedDeadEnd,

    "types.ExtractedDecision": types.ExtractedDecision,
    "stream_types.ExtractedDecision": stream_types.ExtractedDecision,

    "types.ExtractedEntity": types.ExtractedEntity,
    "stream_types.ExtractedEntity": stream_types.ExtractedEntity,

    "types.ExtractedGotcha": types.ExtractedGotcha,
    "stream_types.ExtractedGotcha": stream_types.ExtractedGotcha,

    "types.ExtractedPreference": types.ExtractedPreference,
    "stream_types.ExtractedPreference": stream_types.ExtractedPreference,

    "types.ExtractedReasoningStep": types.ExtractedReasoningStep,
    "stream_types.ExtractedReasoningStep": stream_types.ExtractedReasoningStep,

    "types.ExtractedRelation": types.ExtractedRelation,
    "stream_types.ExtractedRelation": stream_types.ExtractedRelation,

    "types.MemoryExtraction": types.MemoryExtraction,
    "stream_types.MemoryExtraction": stream_types.MemoryExtraction,

    "types.ReasoningChainInput": types.ReasoningChainInput,
    "stream_types.ReasoningChainInput": stream_types.ReasoningChainInput,

    "types.ReasoningExtractionOutput": types.ReasoningExtractionOutput,
    "stream_types.ReasoningExtractionOutput": stream_types.ReasoningExtractionOutput,

    "types.ReasoningStepInput": types.ReasoningStepInput,
    "stream_types.ReasoningStepInput": stream_types.ReasoningStepInput,

    "types.TemporalExtraction": types.TemporalExtraction,
    "stream_types.TemporalExtraction": stream_types.TemporalExtraction,


    "types.EntityType": types.EntityType,

}