# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectContradictions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ContradictionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectContradictions", llm_response=llm_response, mode="request")
        return typing.cast(types.ContradictionResult, __result__)

    def ExtractMemory(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MemoryExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMemory", llm_response=llm_response, mode="request")
        return typing.cast(types.MemoryExtraction, __result__)

    def ExtractReasoning(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ReasoningExtractionOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractReasoning", llm_response=llm_response, mode="request")
        return typing.cast(types.ReasoningExtractionOutput, __result__)

    def ExtractTemporalContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TemporalExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTemporalContext", llm_response=llm_response, mode="request")
        return typing.cast(types.TemporalExtraction, __result__)

    def SynthesizeExplanation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeExplanation", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectContradictions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ContradictionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectContradictions", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ContradictionResult, __result__)

    def ExtractMemory(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MemoryExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMemory", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MemoryExtraction, __result__)

    def ExtractReasoning(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ReasoningExtractionOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractReasoning", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ReasoningExtractionOutput, __result__)

    def ExtractTemporalContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TemporalExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTemporalContext", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TemporalExtraction, __result__)

    def SynthesizeExplanation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeExplanation", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    