# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CandidateFact": types.CandidateFact,
    "stream_types.CandidateFact": stream_types.CandidateFact,

    "types.ContradictionResult": types.ContradictionResult,
    "stream_types.ContradictionResult": stream_types.ContradictionResult,

    "types.ExtractedEntity": types.ExtractedEntity,
    "stream_types.ExtractedEntity": stream_types.ExtractedEntity,

    "types.ExtractedPreference": types.ExtractedPreference,
    "stream_types.ExtractedPreference": stream_types.ExtractedPreference,

    "types.ExtractedReasoningStep": types.ExtractedReasoningStep,
    "stream_types.ExtractedReasoningStep": stream_types.ExtractedReasoningStep,

    "types.ExtractedRelation": types.ExtractedRelation,
    "stream_types.ExtractedRelation": stream_types.ExtractedRelation,

    "types.ExtractionOutput": types.ExtractionOutput,
    "stream_types.ExtractionOutput": stream_types.ExtractionOutput,

    "types.MeetingEntity": types.MeetingEntity,
    "stream_types.MeetingEntity": stream_types.MeetingEntity,

    "types.MeetingExtractionOutput": types.MeetingExtractionOutput,
    "stream_types.MeetingExtractionOutput": stream_types.MeetingExtractionOutput,

    "types.MeetingRelation": types.MeetingRelation,
    "stream_types.MeetingRelation": stream_types.MeetingRelation,

    "types.ProjectEntity": types.ProjectEntity,
    "stream_types.ProjectEntity": stream_types.ProjectEntity,

    "types.ProjectExtractionOutput": types.ProjectExtractionOutput,
    "stream_types.ProjectExtractionOutput": stream_types.ProjectExtractionOutput,

    "types.ProjectRelation": types.ProjectRelation,
    "stream_types.ProjectRelation": stream_types.ProjectRelation,

    "types.ReasoningChainInput": types.ReasoningChainInput,
    "stream_types.ReasoningChainInput": stream_types.ReasoningChainInput,

    "types.ReasoningExtractionOutput": types.ReasoningExtractionOutput,
    "stream_types.ReasoningExtractionOutput": stream_types.ReasoningExtractionOutput,

    "types.ReasoningStepInput": types.ReasoningStepInput,
    "stream_types.ReasoningStepInput": stream_types.ReasoningStepInput,

    "types.RerankOutput": types.RerankOutput,
    "stream_types.RerankOutput": stream_types.RerankOutput,

    "types.ResearchEntity": types.ResearchEntity,
    "stream_types.ResearchEntity": stream_types.ResearchEntity,

    "types.ResearchExtractionOutput": types.ResearchExtractionOutput,
    "stream_types.ResearchExtractionOutput": stream_types.ResearchExtractionOutput,

    "types.ResearchRelation": types.ResearchRelation,
    "stream_types.ResearchRelation": stream_types.ResearchRelation,

    "types.ResultItem": types.ResultItem,
    "stream_types.ResultItem": stream_types.ResultItem,

    "types.RoutingDecision": types.RoutingDecision,
    "stream_types.RoutingDecision": stream_types.RoutingDecision,

    "types.RoutingTarget": types.RoutingTarget,
    "stream_types.RoutingTarget": stream_types.RoutingTarget,

    "types.ScoredResult": types.ScoredResult,
    "stream_types.ScoredResult": stream_types.ScoredResult,

    "types.TemporalExtraction": types.TemporalExtraction,
    "stream_types.TemporalExtraction": stream_types.TemporalExtraction,


    "types.EntityType": types.EntityType,

    "types.MeetingEntityType": types.MeetingEntityType,

    "types.ProjectEntityType": types.ProjectEntityType,

    "types.QueryVertical": types.QueryVertical,

    "types.ResearchEntityType": types.ResearchEntityType,

}