# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class EntityType(str, Enum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    LOCATION = "LOCATION"
    EVENT = "EVENT"
    OBJECT = "OBJECT"
    MEETING = "MEETING"
    AGENDA_ITEM = "AGENDA_ITEM"
    ACTION_ITEM = "ACTION_ITEM"
    DECISION = "DECISION"
    PROJECT = "PROJECT"
    TASK = "TASK"
    MILESTONE = "MILESTONE"
    DELIVERABLE = "DELIVERABLE"
    NOTE = "NOTE"
    FINDING = "FINDING"
    SOURCE = "SOURCE"
    TOPIC = "TOPIC"
    EXPERIMENT = "EXPERIMENT"

# #########################################################################
# Generated classes (11)
# #########################################################################

class CandidateFact(BaseModel):
    idx: int = Field(description='Index of this fact in the candidates list')
    subject: str
    predicate: str
    object: str
    confidence: float

class ContradictionResult(BaseModel):
    contradicted_indices: typing.List[int] = Field(description='Indices of candidate facts that are contradicted by the new fact. Empty if no contradictions.')
    contradiction_type: str = Field(description='Type: \'direct_supersession\' (same subject, updated value), \'negation\' (opposite claim), \'refinement\' (more specific version), or \'none\'')
    reasoning: str = Field(description='Brief explanation of why these facts are contradicted')

class ExtractedEntity(BaseModel):
    name: str = Field(description='The entity name as it appears in text')
    type: EntityType
    subtype: typing.Optional[str] = Field(default=None, description='Optional finer type, e.g. VEHICLE for OBJECT, STANDUP for MEETING')
    status: typing.Optional[str] = Field(default=None, description='Lifecycle status when stated: e.g. scheduled/completed/cancelled (meetings), active/blocked/done/planned (tasks, projects), draft/validated/refuted (research)')
    priority: typing.Optional[str] = Field(default=None, description='Priority when stated: critical, high, medium, low')
    date: typing.Optional[str] = Field(default=None, description='A date/time associated with the entity, ISO 8601 (YYYY-MM-DD) preferred')
    confidence: float = Field(description='Extraction confidence from 0.0 to 1.0')

class ExtractedPreference(BaseModel):
    category: str = Field(description='Preference category: food, music, tech, communication, style, etc.')
    preference: str = Field(description='The preference statement')
    context: typing.Optional[str] = Field(default=None, description='When/where this preference applies')
    confidence: float = Field(description='Preference confidence from 0.0 to 1.0')

class ExtractedReasoningStep(BaseModel):
    thought: str = Field(description='The reasoning or hypothesis behind the action — WHY it was done')
    action: str = Field(description='What action was taken or decision made')
    observation: str = Field(description='What was learned or observed from the action')
    alternatives_considered: typing.Optional[str] = Field(default=None, description='Other approaches that were weighed and rejected')
    confidence: float = Field(description='Confidence in the extraction, 0.0 to 1.0')

class ExtractedRelation(BaseModel):
    source: str = Field(description='Source entity name (must match an extracted entity)')
    target: str = Field(description='Target entity name (must match an extracted entity)')
    relation_type: str = Field(description='UPPER_SNAKE_CASE relationship. Generic: WORKS_AT, MEMBER_OF, LIVES_IN, LOCATED_IN, OWNS, KNOWS, PART_OF. Meetings: ATTENDED, PRESENTED, DISCUSSED, DECIDED_IN, SCHEDULED_FOR, ASSIGNED_TO, FOLLOW_UP, RESULTED_IN. Projects: DEPENDS_ON, BLOCKED_BY, DELIVERS, CONTRIBUTES_TO, TRACKS. Research: CITES, SUPPORTS, CONTRADICTS, BUILDS_ON, EXPLORES, PRODUCED_BY, VALIDATES. Cross-domain: ABOUT, REFERENCES.')
    confidence: float = Field(description='Relation confidence from 0.0 to 1.0')

class MemoryExtraction(BaseModel):
    entities: typing.List["ExtractedEntity"]
    relations: typing.List["ExtractedRelation"]
    preferences: typing.List["ExtractedPreference"]

class ReasoningChainInput(BaseModel):
    task: str = Field(description='The task that was solved')
    steps: typing.List["ReasoningStepInput"] = Field(description='The reasoning steps taken')
    outcome: str = Field(description='The final outcome')

class ReasoningExtractionOutput(BaseModel):
    task: str = Field(description='The overall task or question being addressed')
    steps: typing.List["ExtractedReasoningStep"] = Field(description='The reasoning steps in chronological order')
    final_conclusion: str = Field(description='The final conclusion or answer reached')
    success: bool = Field(description='Whether the task was successfully completed')

class ReasoningStepInput(BaseModel):
    thought: str = Field(description='Why this action was chosen')
    action: str = Field(description='What was done')
    observation: str = Field(description='What was learned')

class TemporalExtraction(BaseModel):
    valid_at: typing.Optional[str] = Field(default=None, description='Extracted datetime when fact became true, in ISO 8601. E.g., \'2026-03-01T00:00:00Z\'. null if not determinable.')
    temporal_qualifier: typing.Optional[str] = Field(default=None, description='Temporal qualifier: \'since\', \'until\', \'as_of\', \'formerly\', \'currently\', or null')
    is_current_state: bool = Field(description='True if this describes the current state of affairs, false if explicitly past tense')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
